# Copyright 2023 SECO Mind Srl
# SPDX-License-Identifier: Apache-2.0

name: reuse

permissions:
  contents: read

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v2
